/** @file traceback.h
 *  @brief Function prototype(s) for traceback library
 *
 *  DO NOT EDIT THIS FILE
 *
 *  @author Michael Ashley-Rollman(mpa)
 */

#ifndef __traceback_h_
#define __traceback_h_

#include <stdio.h>

/*
 * The traceback function that is the heart of the library
 */
void traceback(FILE *);

#endif /* __traceback_h_ */
